CREATE TABLE restaurants  (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    price_range INTEGER NOT NULL check(price_range >= 1 and price_range <= 5)
);