CREATE TABLE reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    rating INTEGER NOT NULL check(rating >= 1 and rating <= 5)
);

ALTER TABLE reviews
    ADD COLUMN
    restaurant_id INTEGER REFERENCES restaurants(id) ON DELETE CASCADE NOT NULL;